spring.application.name=EksamenBackend


spring.datasource.url=${URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
















#create (sletter databasen og laver den om hvergang)
#none(jpa hipernate g�r i ddl) goer ingenting i hipernate,
#create-drop(opretter og sletter tabellen hver gang
#validate(Sammenligner, hvis der forskel i databasen og i modelklasserne s� stopper den programmet og giver fejl),